### PR TITLE
Photo Thumbnail,mother_name edit and Deleting in view

### PR DESCRIPTION
**Pull request by rjsiva**
Thanks for the updation from Mr.Thamaraiselvan. Its seems class= mandatory is working fine.Just made the two scripts under single validate_photo script.Also removed the old photo in the child_detail_views.py when the new photo is get updated (Which is not done for so long as old photos are accumulating in the server).Can be tested and merged if it solves all the issues.

### CODE REVIEW

**Comment by emisteam** [comment]
team members pls comment

**Comment by mageshsugu** [comment]
@rjsiva  pls remove the host address in settings.py as this creates a conflict and then commit

**Comment by emisteam** [comment]
merging this commit after resolving one conflict

**Comment by rjsiva** [comment]
Before pushing into the GITHUB , Kindly run  $find . -name "*.pyc" type -f delete ( To delete all the .pyc files in the project) to get the exact changes made in the project .

**Comment by mageshsugu** [comment]
Already merged your pr. No need to worry .because each time a member
commits all pyc files will be added. I can delete them from repo and
history. But I advice to delete them before you commit

**Comment by rjsiva** [comment]
Yes, I just suggesting the point to everyone , to reflect the remarks in  the specific code changes made by him.

**Pull request merged**
