### PR TITLE
Aadhaar Report and DEE District Progress Report

### PR DESCRIPTION
**Pull request by jenefabrando**
Aadhaar Report for state & district logins and DEE Progress Report for district login.Also made changes in CBSE group code reflecting in student profile and pdf download.Redirection of child updation to respective student profile.

### CODE REVIEW

**Comment by emisteam** [comment]
@jenefabrando pls  see the above conflicts which has to be addressed.pls update your child_detail_form.html(you have not pulled the last commit by @mravikumar281. once you finish that  i can resolve other conflicts

**Comment by emisteam** [comment]
@palaniappan47 pls comment on the multiple db queries in reports. once you give your feedback i may proceed.

**Comment by emisteam** [comment]
conflicts

**Comment by palaniappan47** [comment]
Cant get your point what do you mean by multiple DB queries ??

**Comment by mageshsugu** [comment]
I mean to say put your comments on this pull request as a DB admin

**Pull request closed without merging**
