### PR TITLE
Class wise abstract visible only for the available classes,Section-wise abstract for each class

### PR DESCRIPTION
**Pull request by jenefabrando**
1. The class wise abstract is made visible only for the available classes based on the school category.

2. A new tab named **Section-wise** is added to view the section-wise abstract for each class.

3. In the class wise list view, in addition to the name, unique id ,class, 
the following details i.e) dob, father name, aadhaar no., photo, group code for 11&12, dob is also shown.

4.While creating and updating student data, an acknowledgement showing the particular student name, dob, gender and unique id is received.

### CODE REVIEW

**Comment by mageshsugu** [comment]
Dear Team please check and comment on this commit so that i can merge the code

**Comment by emisteam** [comment]
@jenefabrando 
1.the class wise  list based on school catogory works fine.
2.section wise tab list students with transfer flag 2 also. this should be corrected.
3. in class wise view list section can also be added 
  pls do the corrections needed and create a new pull request.(also pls close this pull request)

**Comment by preamji** [comment]
section wise tab list students with transfer flag 2 also. this should be corrected.(STATEMENT IS NOT CLEAR )

**Comment by emisteam** [comment]
@preamji 
IN CLASS WISE LIST AND SECTION WISE LIST STUDENTS WITH TRANSFER FLAG 2 SHOULD NOT BE COUNTED FOR AS THEY BELONG TO STUDENT POOL. GO THROUGH " TRANSFERING STUDENTS TO COMMON POOL AND ABSORBING THEM" TO GET AN IDEA.

**Pull request closed without merging**
